# This is a basic workflow to help you get started with Actions

name: Merge
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: feature1
   # Jobs to be executed
jobs:
    pmd-run:
        runs-on: ubuntu-latest
        steps:
        # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v2

            # Install PMD
            - name: 'Install PMD'
              run: |
                  PMD_VERSION=`cat pmd/pmd-version.txt`
                  wget https://github.com/pmd/pmd/releases/download/pmd_releases%2F$PMD_VERSION/pmd-bin-$PMD_VERSION.zip
                  unzip pmd-bin-$PMD_VERSION.zip -d ~
                  mv ~/pmd-bin-$PMD_VERSION ~/pmd
                  ~/pmd/bin/run.sh pmd --version
            # Run PMD scan
            - name: 'Run PMD scan'
              run: ~/pmd/bin/run.sh pmd -d force-app -R pmd/ruleset.xml -f text
    feature-merge-main:
        runs-on: ubuntu-latest 
        steps:
        - name: Merge staging -> uat
          uses: devmasx/merge-branch@master
          with:
            type: now
            from_branch: feature1
            target_branch: master
            github_token: ${{ secrets.GITHUB_TOKEN }}
